# Generated by Django 3.2.6 on 2021-09-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactinfo_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
