# Generated by Django 3.2.6 on 2021-10-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_ar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image_ar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img', verbose_name='image'),
        ),
    ]
