# Generated by Django 3.2.6 on 2021-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211008_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
    ]
