# Generated by Django 3.2.6 on 2021-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=100, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
