# Generated by Django 3.2.6 on 2021-08-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='CATSLug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
