# Generated by Django 3.2.6 on 2021-08-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_catslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CATSLug',
        ),
    ]
