# Generated by Django 3.2.6 on 2021-09-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_catslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CATsLug',
            new_name='CATslug',
        ),
    ]
