# Generated by Django 3.2.6 on 2021-10-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_customer_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tele',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
