# Generated by Django 3.2.6 on 2021-10-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_customer_tele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tele',
        ),
    ]
