# Generated by Django 3.2.6 on 2021-10-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_customer_tele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Mobile (المحمول)'),
        ),
    ]
