# Generated by Django 3.2.6 on 2021-10-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_customer_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='phone',
        ),
    ]
